apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.service.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.service.name }}
  minReplicas: 3
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50